In [1]:
import pandas  as pd
df=pd.read_csv("dataset_facebook.csv",delimiter=";")

In [2]:
df


Page total likes    Type  Category  Post Month  Post Weekday  Post Hour  \
0              139441   Photo         2          12             4          3   
1              139441  Status         2          12             3         10   
2              139441   Photo         3          12             3          3   
3              139441   Photo         2          12             2         10   
4              139441   Photo         2          12             2          3   
..                ...     ...       ...         ...           ...        ...   
495             85093   Photo         3           1             7          2   
496             81370   Photo         2           1             5          8   
497             81370   Photo         1           1             5          2   
498             81370   Photo         3           1             4         11   
499             81370   Photo         2           1             4          4   

     Paid  Lifetime Post Total Reach  Lifetime Post Total Impressions  \
0     0.0                       2752                             5091   
1     0.0                      10460                            19057   
2     0.0                       2413                             4373   
3     1.0                      50128                            87991   
4     0.0                       7244                            13594   
..    ...                        ...                              ...   
495   0.0                       4684                             7536   
496   0.0                       3480                             6229   
497   0.0                       3778                             7216   
498   0.0                       4156                             7564   
499   NaN                       4188                             7292   

     Lifetime Engaged Users  Lifetime Post Consumers  \
0                       178                      109   
1                      1457                     1361   
2                       177                      113   
3                      2211                      790   
4                       671                      410   
..                      ...                      ...   
495                     733                      708   
496                     537                      508   
497                     625                      572   
498                     626                      574   
499                     564                      524   

     Lifetime Post Consumptions  \
0                           159   
1                          1674   
2                           154   
3                          1119   
4                           580   
..                          ...   
495                         985   
496                         687   
497                         795   
498                         832   
499                         743   

     Lifetime Post Impressions by people who have liked your Page  \
0                                                 3078              
1                                                11710              
2                                                 2812              
3                                                61027              
4                                                 6228              
..                                                 ...              
495                                               4750              
496                                               3961              
497                                               4742              
498                                               4534              
499                                               3861              

     Lifetime Post reach by people who like your Page  \
0                                                1640   
1                                                6112   
2                                                1503   
3               

In [ ]:
create subset

In [4]:
subset1=df[['Type','Category','Post Month']]
print(subset1.head())

     Type  Category  Post Month
0   Photo         2          12
1  Status         2          12
2   Photo         3          12
3   Photo         2          12
4   Photo         2          12


In [5]:
subset2=df[['Type','Category','comment']]
print(subset2.head())

     Type  Category  comment
0   Photo         2        4
1  Status         2        5
2   Photo         3        0
3   Photo         2       58
4   Photo         2       19


In [6]:
merged=pd.concat([subset1,subset2],axis=1)

In [7]:
merged


Type  Category  Post Month    Type  Category  comment
0     Photo         2          12   Photo         2        4
1    Status         2          12  Status         2        5
2     Photo         3          12   Photo         3        0
3     Photo         2          12   Photo         2       58
4     Photo         2          12   Photo         2       19
..      ...       ...         ...     ...       ...      ...
495   Photo         3           1   Photo         3        5
496   Photo         2           1   Photo         2        0
497   Photo         1           1   Photo         1        4
498   Photo         3           1   Photo         3        7
499   Photo         2           1   Photo         2        0

[500 rows x 6 columns]

In [ ]:
//sort values

In [9]:
merged.sort_values(by=['comment'],ascending=False)

Type  Category  Post Month   Type  Category  comment
244  Photo         2           7  Photo         2      372
460  Photo         3           2  Photo         3      146
168  Photo         1           9  Photo         1      144
288  Photo         1           6  Photo         1      103
228  Photo         2           7  Photo         2       64
..     ...       ...         ...    ...       ...      ...
332  Photo         3           5  Photo         3        0
333  Photo         3           5  Photo         3        0
111  Photo         1          10  Photo         1        0
103  Photo         1          10  Photo         1        0
499  Photo         2           1  Photo         2        0

[500 rows x 6 columns]

In [10]:
merged.T

0       1      2      3      4       5      6      7       8    \
Type        Photo  Status  Photo  Photo  Photo  Status  Photo  Photo  Status   
Category        2       2      3      2      2       2      3      3       2   
Post Month     12      12     12     12     12      12     12     12      12   
Type        Photo  Status  Photo  Photo  Photo  Status  Photo  Photo  Status   
Category        2       2      3      2      2       2      3      3       2   
comment         4       5      0     58     19       1      3      0       0   

              9    ...    490    491   492    493    494    495    496    497  \
Type        Photo  ...  Photo  Photo  Link  Photo  Photo  Photo  Photo  Photo   
Category        3  ...      3      3     1      3      3      3      2      1   
Post Month     12  ...      1      1     1      1      1      1      1      1   
Type        Photo  ...  Photo  Photo  Link  Photo  Photo  Photo  Photo  Photo   
Category        3  ...      3      3     1      3      3      3      2      1   
comment         3  ...      1      1     0     17     10      5      0      4   

              498    499  
Type        Photo  Photo  
Category        3      2  
Post Month      1      1  
Type        Photo  Photo  
Category        3      2  
comment         7      0  

[6 rows x 500 columns]

In [11]:
merged.transpose()

0       1      2      3      4       5      6      7       8    \
Type        Photo  Status  Photo  Photo  Photo  Status  Photo  Photo  Status   
Category        2       2      3      2      2       2      3      3       2   
Post Month     12      12     12     12     12      12     12     12      12   
Type        Photo  Status  Photo  Photo  Photo  Status  Photo  Photo  Status   
Category        2       2      3      2      2       2      3      3       2   
comment         4       5      0     58     19       1      3      0       0   

              9    ...    490    491   492    493    494    495    496    497  \
Type        Photo  ...  Photo  Photo  Link  Photo  Photo  Photo  Photo  Photo   
Category        3  ...      3      3     1      3      3      3      2      1   
Post Month     12  ...      1      1     1      1      1      1      1      1   
Type        Photo  ...  Photo  Photo  Link  Photo  Photo  Photo  Photo  Photo   
Category        3  ...      3      3     1      3      3      3      2      1   
comment         3  ...      1      1     0     17     10      5      0      4   

              498    499  
Type        Photo  Photo  
Category        3      2  
Post Month      1      1  
Type        Photo  Photo  
Category        3      2  
comment         7      0  

[6 rows x 500 columns]

In [13]:
df.shape

(500, 19)

In [14]:
# Reshape ke liye pehle values ko array bana lete hain
import numpy as np

arr = np.array(df[['Post Month', 'Post Weekday']].head(6))
reshaped = arr.reshape(3, 4)
print(reshaped)


[[12  4 12  3]
 [12  3 12  2]
 [12  2 12  1]]
